apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k3n0u3ogy-nodejs
  janus-idp.io/tekton: k3n0u3ogy-nodejs
  backstage.io/kubernetes-id: k3n0u3ogy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k3n0u3ogy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
