apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k3n0u3ogy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k3n0u3ogy-nodejs 
  name: k3n0u3ogy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: k3n0u3ogy-nodejs 
